// ──────────────────────────────────────────────
// Preset templates catalogue
// ──────────────────────────────────────────────
export const TEMPLATE_PRESETS = [
  {
    id: 'elegant-gold',
    name: 'Élégance Dorée',
    category: 'Mariage',
    emoji: '💍',
    template: {
      style: 'elegant',
      primaryColor: '#d4af37',
      secondaryColor: '#c9a27e',
      bgColor: '#0f0c08',
      bgGradient: ['#1a1408', '#0f0c05'],
      bgImage: null,
      textColor: '#f5f0e8',
      accentColor: '#d4af37',
      fontFamily: 'Cormorant Garamond, Georgia, serif',
      headerFontSize: '3.5rem',
      bodyFontSize: '1.1rem',
      borderStyle: 'double',
      borderColor: '#d4af37',
      borderOpacity: 0.6,
      cornerDecoration: true,
      floral: false,
      glitter: true,
      headerText: 'Vous êtes invité(e)',
      subHeaderText: 'à notre célébration',
      buttonLabel: 'RSVP Maintenant',
      buttonColor: '#d4af37',
      buttonTextColor: '#0f0c08',
    }
  },
  {
    id: 'romantic-rose',
    name: 'Romance Rosée',
    category: 'Mariage',
    emoji: '🌹',
    template: {
      style: 'romantic',
      primaryColor: '#e8b4b8',
      secondaryColor: '#d4a5a5',
      bgColor: '#2d1f2f',
      bgGradient: ['#2d1f2f', '#1a1020'],
      bgImage: null,
      textColor: '#f9e8e8',
      accentColor: '#ff8fab',
      fontFamily: 'Playfair Display, Georgia, serif',
      headerFontSize: '3rem',
      bodyFontSize: '1rem',
      borderStyle: 'solid',
      borderColor: '#e8b4b8',
      borderOpacity: 0.5,
      cornerDecoration: true,
      floral: true,
      glitter: false,
      headerText: 'Avec amour',
      subHeaderText: 'nous vous invitons',
      buttonLabel: 'Confirmer ma présence',
      buttonColor: '#e8b4b8',
      buttonTextColor: '#2d1f2f',
    }
  },
  {
    id: 'modern-minimal',
    name: 'Minimalisme Moderne',
    category: 'Professionnel',
    emoji: '✨',
    template: {
      style: 'modern',
      primaryColor: '#6366f1',
      secondaryColor: '#8b5cf6',
      bgColor: '#09090b',
      bgGradient: ['#09090b', '#18181b'],
      bgImage: null,
      textColor: '#fafafa',
      accentColor: '#a78bfa',
      fontFamily: 'Inter, system-ui, sans-serif',
      headerFontSize: '2.8rem',
      bodyFontSize: '1rem',
      borderStyle: 'solid',
      borderColor: '#6366f1',
      borderOpacity: 0.3,
      cornerDecoration: false,
      floral: false,
      glitter: false,
      headerText: 'You are invited',
      subHeaderText: 'to an exclusive event',
      buttonLabel: 'RSVP',
      buttonColor: '#6366f1',
      buttonTextColor: '#ffffff',
    }
  },
  {
    id: 'festive-party',
    name: 'Grande Fête',
    category: 'Anniversaire',
    emoji: '🎉',
    template: {
      style: 'festive',
      primaryColor: '#f59e0b',
      secondaryColor: '#ef4444',
      bgColor: '#1c0a00',
      bgGradient: ['#1c0a00', '#2d1500'],
      bgImage: null,
      textColor: '#fff7ed',
      accentColor: '#fbbf24',
      fontFamily: 'Poppins, system-ui, sans-serif',
      headerFontSize: '3.2rem',
      bodyFontSize: '1.1rem',
      borderStyle: 'dashed',
      borderColor: '#f59e0b',
      borderOpacity: 0.7,
      cornerDecoration: false,
      floral: false,
      glitter: true,
      headerText: 'C\'est la fête !',
      subHeaderText: 'rejoignez-nous pour célébrer',
      buttonLabel: 'Je serai là ! 🎊',
      buttonColor: '#f59e0b',
      buttonTextColor: '#1c0a00',
    }
  },
  {
    id: 'nature-garden',
    name: 'Jardin Nature',
    category: 'Mariage',
    emoji: '🌿',
    template: {
      style: 'nature',
      primaryColor: '#6b8e6b',
      secondaryColor: '#8fbc8f',
      bgColor: '#0a1a0a',
      bgGradient: ['#0a1a0a', '#0d200d'],
      bgImage: null,
      textColor: '#f0fdf0',
      accentColor: '#86efac',
      fontFamily: 'Lora, Georgia, serif',
      headerFontSize: '3rem',
      bodyFontSize: '1rem',
      borderStyle: 'solid',
      borderColor: '#6b8e6b',
      borderOpacity: 0.5,
      cornerDecoration: true,
      floral: true,
      glitter: false,
      headerText: 'Rejoignez-nous',
      subHeaderText: 'dans notre jardin',
      buttonLabel: 'Répondre',
      buttonColor: '#6b8e6b',
      buttonTextColor: '#ffffff',
    }
  },
  {
    id: 'cosmic-luxury',
    name: 'Luxe Cosmique',
    category: 'Gala',
    emoji: '🌌',
    template: {
      style: 'cosmic',
      primaryColor: '#9d4edd',
      secondaryColor: '#7b2cbf',
      bgColor: '#050010',
      bgGradient: ['#050010', '#0a0020'],
      bgImage: null,
      textColor: '#f0e6ff',
      accentColor: '#c77dff',
      fontFamily: 'Cinzel, Georgia, serif',
      headerFontSize: '3.5rem',
      bodyFontSize: '1.1rem',
      borderStyle: 'solid',
      borderColor: '#9d4edd',
      borderOpacity: 0.6,
      cornerDecoration: true,
      floral: false,
      glitter: true,
      headerText: 'An Extraordinary Evening',
      subHeaderText: 'awaits your presence',
      buttonLabel: 'Accept the Invitation',
      buttonColor: '#9d4edd',
      buttonTextColor: '#ffffff',
    }
  }
]
